version: "3"

services:
  postgres:
    container_name: ms-user-email
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydbuseremail
    networks:
      - postgres

volumes:
  postgres:
    driver: local
networks:
  postgres:
    driver: bridge